# Generated by Django 4.2.16 on 2025-11-12 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_bono', models.CharField(choices=[('1_dia', '1 Día Extra'), ('2_dias', '2 Días Extra'), ('3_dias', '3 Días Extra')], max_length=20)),
                ('dias_regalo', models.IntegerField(default=0)),
                ('motivo', models.CharField(max_length=200)),
                ('fecha_otorgado', models.DateTimeField(auto_now_add=True)),
                ('aplicado', models.BooleanField(default=False)),
                ('fecha_aplicado', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonos', to='gestion.cliente')),
                ('usuario_otorgo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bonos',
                'ordering': ['-fecha_otorgado'],
            },
        ),
    ]
